name: 'Generate access token'
description: 'Generate access token'
inputs:
  gh_app_priv_key:
    description: 'GitHub Application private key'
    required: true
  gh_app_id:
    description: 'GitHub Application ID'
    required: true
  gh_app_installation_id:
    description: 'GitHub Application intallation ID'
    required: true
  action_shell:
    description: 'Define the shell for commands.'
    required: false
    default: bash
outputs:
  token:
    value: ${{ steps.accessToken.outputs.GH_ACCESS_TOKEN}}
runs:
  using: "composite"
  steps:
    - name: 'Checkout code'
      uses: actions/checkout@v4
      with:
        path: gh-access

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: 'Install dependencies'
      run: python -m pip install -r requirements.txt
      shell: ${{ inputs.shell }}

    - id: accessToken
      run: python gh-access/generate_token.py
      env:
        PEM_B64: ${{ inputs.gh_app_priv_key }}
        GH_APP_ID: ${{ inputs.gh_app_id }}
        GH_APP_INSTALLATION_ID: ${{ inputs.gh_app_installation_id }}
      shell: ${{ inputs.shell }}
