name: 'Generate access token'
description: 'Generate access token'
inputs:
  gh_app_priv_key:
    description: 'GitHub Application private key'
    required: true
  gh_app_id:
    description: 'GitHub Application ID'
    required: true
  gh_app_installation_id:
    description: 'GitHub Application intallation ID'
    required: true
  action_shell:
    description: 'Define the shell for commands.'
    required: false
    default: bash
  cmd_python:
    description: 'Define python | python3 for self-hosted runners.'
    required: false
    default: python3
outputs:
  token:
    value: ${{ steps.accessToken.outputs.GH_ACCESS_TOKEN}}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      if: ${{ runner.environment == 'github-hosted' }}
      with:
        python-version: '3.11'

    - name: 'Install dependencies'
      run: ${{ inputs.cmd_python }} -m pip install --no-cache-dir -r ${{ github.action_path }}/requirements.txt
      shell: ${{ inputs.shell }}

    - id: accessToken
      run: ${{ inputs.cmd_python }} ${{ github.action_path }}/generate_token.py
      env:
        PEM_B64: ${{ inputs.gh_app_priv_key }}
        GH_APP_ID: ${{ inputs.gh_app_id }}
        GH_APP_INSTALLATION_ID: ${{ inputs.gh_app_installation_id }}
      shell: ${{ inputs.shell }}
